//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nagarro.BookEventManagement.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DatePosted { get; set; }
        public int UserId { get; set; }
        public int EventId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
